blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/kawaaaas/lambda-env-schema/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
  - name: Documentation
    url: https://github.com/kawaaaas/lambda-env-schema#readme
    about: Check the documentation for usage examples
